version: '3.1'

# access db with docker-compose exec db psql -U postgres
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
